apiVersion: v1
kind: PersistentVolume
metadata:
  name: webnotes-static-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  storageClassName: standard
  hostPath:
    path: /data/static-webnotes
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webnotes-static-pvc
  namespace: webnotes
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi 