# k8s/webnotes-client.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webnotes-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webnotes-client
  template:
    metadata:
      labels:
        app: webnotes-client
    spec:
      containers:
        - name: webnotes-client
          image: jessyfal04/webnotes-client:latest
          ports:
            - containerPort: 8080            # REST + UI
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
            - name: GRPC_SERVER_HOST         # internal call
              value: "webnotes-server"
            - name: GRPC_SERVER_PORT
              value: "9090"
---
apiVersion: v1
kind: Service
metadata:
  name: webnotes-client
spec:
  selector:
    app: webnotes-client
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
