# k8s/webnotes-server.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webnotes-server
  namespace: webnotes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webnotes-server
  template:
    metadata:
      labels:
        app: webnotes-server
    spec:
      containers:
        - name: webnotes-server
          image: jessyfal04/webnotes-server:latest
          ports:
            - containerPort: 9090            # gRPC
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/db?createDatabaseIfNotExist=true"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: SPRING_JPA_SHOW_SQL
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: webnotes-server
  namespace: webnotes
spec:
  selector:
    app: webnotes-server
  ports:
    - name: grpc
      port: 9090
      targetPort: 9090
  type: ClusterIP
